[global]
    frame_color = "#aea084"

[urgency_low]
    background = "#303931"
    foreground = "#9ba3a2"

[urgency_normal]
    background = "#153227"
    foreground = "#b9d3b0"

[urgency_critical]
    background = "#e8a27f"
    foreground = "#153227"
