# -*- conf -*-

# man foot.ini

include=~/.config/foot/active-theme

font=Hack Nerd Font:size=12

pad=20x20 center-when-maximized-and-fullscreen

[scrollback]
lines=2000
multiplier=10.0 # lines per mouse wheel 
indicator-format=line

[cursor]
style=underline

[colors]
alpha=0.97

