[global]
    frame_color = "#819cd6"

[urgency_low]
    background = "#1f2024"
    foreground = "#c6c6c6"

[urgency_normal]
    background = "#282b33"
    foreground = "#c6c6c6"

[urgency_critical]
    background = "#e1c1ee"
    foreground = "#1f2024"
