[global]
    frame_color = "#509475"

[urgency_low]
    background = "#23372B"
    foreground = "#C1C497"

[urgency_normal]
    background = "#111c18"
    foreground = "#C1C497"

[urgency_critical]
    background = "#FF5345"
    foreground = "#F6F5DD"
