[global]
    frame_color = "#0f5420"

[urgency_low]
    background = "#d5c9b5"
    foreground = "#6b5225"

[urgency_normal]
    background = "#e0d8c7"
    foreground = "#3a2018"

[urgency_critical]
    background = "#982500"
    foreground = "#e0d8c7"
