[global]
    frame_color = "#0f62fe"

[urgency_low]
    background = "#f2f4f8"
    foreground = "#525252"

[urgency_normal]
    background = "#ffffff"
    foreground = "#37474F"

[urgency_critical]
    background = "#FF6F00"
    foreground = "#ffffff"
