[global]
    frame_color = "#82fb9c"

[urgency_low]
    background = "#3e4058"
    foreground = "#ddf7ff"

[urgency_normal]
    background = "#0b0c16"
    foreground = "#ddf7ff"

[urgency_critical]
    background = "#50f872"
    foreground = "#0b0c16"
