[global]
    frame_color = "#fabd2f"

[urgency_low]
    background = "#3c3836"
    foreground = "#ebdbb2"

[urgency_normal]
    background = "#282828"
    foreground = "#ebdbb2"

[urgency_critical]
    background = "#fb4934"
    foreground = "#282828"
