[global]
    frame_color = "#268bd2"

[urgency_low]
    background = "#eee8d5"
    foreground = "#657b83"

[urgency_normal]
    background = "#fdf6e3"
    foreground = "#657b83"

[urgency_critical]
    background = "#dc322f"
    foreground = "#fdf6e3"
