[global]
    frame_color = "#78a9ff"

[urgency_low]
    background = "#131313"
    foreground = "#d0d0d0"
    highlight = "#78a9ff"

[urgency_normal]
    background = "#161616"
    foreground = "#d0d0d0"
    highlight = "#78a9ff"

[urgency_critical]
    background = "#ee5396"
    foreground = "#161616"
    highlight = "#161616"
