[global]
    frame_color = "#78a9ff"

[urgency_low]
    background = "#131313"
    foreground = "#dde1e6"

[urgency_normal]
    background = "#161616"
    foreground = "#dde1e6"

[urgency_critical]
    background = "#ee5396"
    foreground = "#161616"
