# Modus Operandi color theme for btop
# https://protesilaos.com/emacs/modus-themes

theme[main_bg]=""
theme_background=false
theme[main_fg]="#000000"
theme[title]="#0031A9"
theme[hi_fg]="#005E8B"
theme[selected_bg]="#C4C4C4"
theme[selected_fg]="#000000"
theme[inactive_fg]="#9F9F9F"
theme[graph_text]="#000000"
theme[meter_bg]="#F2F2F2"
theme[proc_misc]="#005E8B"

theme[cpu_box]="#9F9F9F"
theme[mem_box]="#9F9F9F"
theme[net_box]="#9F9F9F"
theme[proc_box]="#9F9F9F"
theme[div_line]="#9F9F9F"

theme[temp_start]="#006800"
theme[temp_mid]="#6F5500"
theme[temp_end]="#A60000"

theme[cpu_start]="#7F90FF"
theme[cpu_mid]="#0031A9"
theme[cpu_end]="#9FC6FF"

theme[free_start]="#F2F2F2"
theme[free_mid]="#0031A9"
theme[free_end]="#005E8B"

theme[cached_start]="#E0E0E0"
theme[cached_mid]="#C4C4C4"
theme[cached_end]="#0031A9"

theme[available_start]="#006800"
theme[available_mid]="#005E8B"
theme[available_end]="#005F5F"

theme[used_start]="#006800"
theme[used_mid]="#6F5500"
theme[used_end]="#A60000"

theme[download_start]="#7F90FF"
theme[download_mid]="#0031A9"
theme[download_end]="#005E8B"

theme[upload_start]="#972500"
theme[upload_mid]="#A60000"
theme[upload_end]="#6F5500"

theme[process_start]="#006800"
theme[process_mid]="#005E8B"
theme[process_end]="#721045"
