[global]
    frame_color = "#0031A9"

[urgency_low]
    background = "#F2F2F2"
    foreground = "#595959"
    highlight = "#0031A9"

[urgency_normal]
    background = "#FFFFFF"
    foreground = "#000000"
    highlight = "#0031A9"

[urgency_critical]
    background = "#FF8F88"
    foreground = "#000000"
    highlight = "#000000"
