[global]
    frame_color = "#458588"

[urgency_low]
    background = "#ebdbb2"
    foreground = "#3c3836"

[urgency_normal]
    background = "#fbf1c7"
    foreground = "#3c3836"

[urgency_critical]
    background = "#9d0006"
    foreground = "#fbf1c7"
