#+TITLE: My fish config
#+AUTHOR: Arthur Fleck
#+DESCRIPTION: AF's personal fish config.
#+STARTUP: showeverything
#+OPTIONS: toc:3
#+PROPERTY: header-args:shell :tangle config.fish

* ToC :toc:
- [[#interactive][interactive]]
- [[#abbr][abbr]]
  - [[#cd][cd]]
  - [[#git][git]]
  - [[#heavy-hitters][heavy hitters]]
  - [[#tmux][tmux]]
  - [[#nix][nix]]
  - [[#package-managers][package managers]]
  - [[#update-rsync][update: (r)sync]]
  - [[#special-use][special use]]
  - [[#freebsd][FreeBSD]]
- [[#add-to-path][add to $PATH]]
- [[#alias][alias]]
- [[#set-in-nix----export][set in nix? -- export]]
  - [[#export-env-vars][export ENV vars]]
  - [[#editor--visual][EDITOR / VISUAL]]
  - [[#terminal][TERMINAL]]
- [[#greeting][greeting]]
- [[#test-timestamp-and-keybinding][test timestamp and keybinding]]
- [[#stuff-that-should-be-at-the-end][stuff that should be at the end]]

* interactive
#+begin_src shell
if status is-interactive
    # Commands to run in interactive sessions can go here
end
#+end_src

* abbr
** cd
#+begin_src shell
abbr -a cd. 'cd ~/.config'
abbr -a cdc 'cd ~/my/code'
abbr -a cdd 'cd ~/syscfg'
abbr -a cdj "cd ~/my/code/clojure"
abbr -a cdr 'cd ~/my/code/rust'
abbr -a cds 'cd ~/sync'
abbr -a cdx 'cd ~/x'
abbr -a dl 'cd ~/Downloads'
#+end_src
** git 
#+begin_src shell
abbr -a ga 'git add'
abbr -a gb 'git branch'
abbr -a gc 'git commit -m'
abbr -a gca 'git commit --amend --no-edit'
abbr -a gcm 'git checkout main'
abbr -a gco 'git checkout'
abbr -a gd 'git diff'
abbr -a gin 'clear && git status && echo && git log --oneline -10 && echo && git branch && echo && tokei'
abbr -a gitinfo 'git config --get user.name && git config --get user.email'
abbr -a gl 'git log --oneline'
abbr -a gms 'git merge --squash'
abbr -a gr 'git restore'
abbr -a gs 'git status'
abbr -a gsw 'git show'
#+end_src
** heavy hitters
#+begin_src shell
abbr -a sc systemctl
abbr -a r 'clear && /usr/bin/env bb --config $HOME/syscfg/bb.edn $HOME/syscfg/scripts/command_runner.clj'

if type -q code
   abbr -a c. 'code .'
else
   abbr -a c. 'codium .'
end

abbr -a gi 'grep -i'
abbr -a rg 'rg -i'

abbr -a el 'eza -l --group-directories-first --icons'
abbr -a hg 'history | grep -i'

abbr -a t. 'thunar . & disown'
abbr -a cm chezmoi
abbr -a db distrobox

abbr -a lt 'll -th'
# by default, when in nnn, `e` opens a file with $VISUAL
abbr -a n "VISUAL='emacsclient -nw' nnn"
abbr -a o. 'xdg-open .'
abbr -a pnc "protonvpn-cli ks --off && protonvpn-cli ks --permanent && protonvpn-cli c --protocol tcp --fastest" # RIP nice cli 
abbr -a rc rclone
abbr -a rd 'rm -rf'
abbr -a rl 'RUST_LOG=debug'
abbr -a ssa 'sha256sum'
abbr -a ssc 'sha256sum --check --ignore-missing'
abbr -a tl 'tree -L'
abbr -a todo 'rg -i todo --stats'
abbr -a vd vimdiff


if test "$XDG_SESSION_TYPE" = "wayland"
    abbr -a pwdc 'pwd | wl-copy'
else
    abbr -a pwdc 'pwd | xclip -selection clipboard'
end
#+end_src
** tmux
#+begin_src shell
abbr -a t tmux
abbr -a tn 'tmux new-session -s'
abbr -a tl 'tmux list-sessions'
abbr -a ta 'tmux attach-session'
#+end_src
** nix 
When using `nix shell`, `nix build`, `nix develop`, etc with a flake, then pass `--impure` in order to allow use of environment variables.
#+begin_src shell
abbr -a nxr nix run #e.g. 'nix run nixpkgs#hello'
abbr -a nxs nix shell
abbr -a nxd "nix develop --command fish"
abbr -a nxdu "NIXPKGS_ALLOW_UNFREE=1 nix develop --impure --command fish"
abbr -a nxfu nix flake update

abbr -a nxclean 'nh clean all --keep 3 -n'
abbr -a nxcleanb 'nh clean all --keep 3 --nogcroots -n'
abbr -a nxclean2 'nh clean all --keep-since 7d3h --nogcroots -n'

abbr -a nxgc1 'sudo nix-collect-garbage -d'
abbr -a nxgc2 'sudo nix-collect-garbage --delete-older-than 10d'
abbr -a nxgc3 'nix-store --optimise -vv'
#+end_src
** package managers
#+begin_src shell
abbr -a cg cargo
abbr -a cgb 'cargo build'
abbr -a cgc cargo check
abbr -a cgi 'cargo install --path .'
abbr -a cgr 'cargo run'
abbr -a cgt 'cargo test'
abbr -a fp flatpak
abbr -a fpl flatpak list --app
abbr -a fpu flatpak update
abbr -a pm 'pacman -S'
abbr -a pmq 'pacman -Q'
abbr -a zy zypper

# Extract the distro ID from /etc/os-release, removing any quotes
#set distro (grep -oP '^ID=\K.*' /etc/os-release | tr -d '"')
set distro (awk -F= '/^ID=/ { gsub(/["\047]/, "", $2); print $2 }' /etc/os-release)

switch $distro
    case debian ubuntu linuxmint
        abbr -a up 'sudo apt update && sudo apt upgrade'
        alias bat='batcat'
        alias fd='fdfind'
        abbr -a nf "clear && fastfetch"
    case arch
        abbr -a up 'sudo pacman -Syu'
        abbr -a nf "clear && fastfetch"
    case opensuse-tumbleweed
        abbr -a up 'sudo zypper ref && sudo zypper dup'
        abbr -a nf "clear && fastfetch --logo opensuse"
    case nixos
         abbr -a up "sudo nixos-rebuild switch --flake ~/syscfg/nixos#$hostname"
         abbr -a upb "sudo nixos-rebuild boot --flake ~/syscfg/nixos#$hostname"
         abbr -a upd "nixos-rebuild dry-run --flake ~/syscfg/nixos#$hostname"
         abbr -a up2 "NH_OS_FLAKE=~/syscfg/nixos nh os switch --ask --hostname $hostname"
         abbr -a up2b "NH_OS_FLAKE=~/syscfg/nixos nh os boot --ask --hostname $hostname"
         abbr -a nxup "NH_OS_FLAKE=~/syscfg/nixos nh os switch --ask --hostname $hostname"
         abbr -a nf "clear && fastfetch"
    case void
        abbr -a up 'sudo xbps-install -Su'
        abbr -a nf "clear && fastfetch"
    case fedora
        abbr -a up 'sudo dnf upgrade --refresh'
        abbr -a nf "clear && fastfetch"
    case freebsd
        abbr -a nf "clear && fastfetch --config neofetch"
    case '*'
        abbr -a up 'Unknown distribution. KEKW'
        abbr -a nf "clear && fastfetch"
end

switch $distro
    case arch
         #abbr -a cu "checkupdates | sed 's/->//g' | column -t"
         abbr -a cu $HOME/syscfg/scripts/bb/checkupdates.clj
    case fedora
         abbr -a cu "dnf check-update --refresh | wc -l"
    case nixos
         abbr -a cu "cd ~/syscfg/nixos/ && nix flake update && git status && printf '\n----------\n\n' && nixos-rebuild dry-run --flake ~/syscfg/nixos#$hostname"
         abbr -a lg 'nixos-rebuild list-generations | head'
    case '*'
         abbr -a cu "(checkupdate) Don't know how to on $distro"
end
#+end_src
** TODO update: (r)sync
--inplace is needed with mtp, w/o it we have I/O error when rsync tries renaming the tmp copy foo.mp3.RtlGdU to foo.mp3
#+begin_src shell
abbr -a syncmoto-music "rsync -ahvP --stats '$HOME/mukke/' '/run/user/1000/gvfs/mtp:host=motorola_moto_g54_5G_ZY22HWD8XQ/Internal shared storage/Music/mukke/' --delete --omit-dir-times --no-perms --inplace --size-only --ignore-existing -n"
abbr -a syncmoto-pics "rsync -ahvP --stats '/run/user/1000/gvfs/mtp:host=motorola_moto_g54_5G_ZY22HWD8XQ/Internal shared storage/DCIM' '$HOME/sync/Moto/' -n"
abbr -a syncmoto-backup "rsync -ahvP --stats '/run/user/1000/gvfs/mtp:host=motorola_moto_g54_5G_ZY22HWD8XQ/Internal shared storage/backups' '$HOME/sync/Moto/' -n"

abbr -a sync-pixel-music "rsync -ahvP --stats ~/mukke/ /run/user/1000/gvfs/mtp:host=Google_Pixel_7a_37211JEHN10476/Internal\ shared\ storage/mukke/ --omit-dir-times --no-perms --inplace --size-only --ignore-existing -n"

abbr -a sync-pixel-backup "rsync -ahvP --stats --no-g '/run/user/1000/gvfs/mtp:host=Google_Pixel_6a_25281JEGR07582/Internal shared storage/backup' '/nas/data/backup/pixel6a' -n"

abbr -a sync-pixel-pics "rsync -ahvP --stats --no-g '/run/user/1000/gvfs/mtp:host=Google_Pixel_6a_25281JEGR07582/Internal shared storage/DCIM' '/nas/data/backup/pixel6a' -n"
#+end_src
*** TODO try =adb push= rsync is slow

** special use
Not used often, but very useful.
#+begin_src shell
# official example:                     ffmpeg                 -i input.wav -codec:a libmp3lame -qscale:a 2 output.mp3
abbr -a flac2mp3 'fd -e flac --exec ffmpeg -loglevel error -i {} -codec:a libmp3lame -qscale:a 1 {.}.mp3'

abbr -a ytdlp-split-audio "yt-dlp --format ba[ext=m4a] --split-chapters URL"

abbr -a bk bin/kamal
abbr -a br bin/rails
abbr -a dcc 'steam-run $HOME/syscfg/scripts/bb/dict.cc.clj'
abbr -a ff rfv
abbr -a ffa rfvuuu
abbr -a rcp 'rclone copy --progress'
abbr -a rct 'rclone tree --level 2'
#+end_src
** FreeBSD
#+begin_src shell
abbr -a ifc ifconfig
#+end_src
* add to $PATH
#+begin_src shell
fish_add_path ~/.cargo/bin/
fish_add_path ~/.config/emacs/bin/
fish_add_path ~/.local/bin
#+end_src

* alias
#+begin_src shell
alias e "emacs -nw"
alias v vim
alias l 'eza -l --group-directories-first --icons'
alias lll 'eza -al --group-directories-first --icons'
alias x '/usr/bin/env bb ~/x/x.clj'
#+end_src

* TODO set in nix? -- export
** export ENV vars
#+begin_src shell
# --export -x is the same
set -Ux RESTIC_PASSWORD_FILE "/home/ax/.restic-std"
set -g theme_color_scheme "nord"
set -Ux PAGER less
#+end_src

** EDITOR / VISUAL
#+begin_src shell
export ALTERNATE_EDITOR=""
export EDITOR="emacsclient -nw"
export VISUAL="emacsclient -c"
#+end_src

** TERMINAL
For man pages, Tumbleweed set MAN_POSIXLY_CORRECT to avoid choosing which man page to display each time
- tee(1): User Commands
- tee(2): System Calls Manual
- ...

#+begin_src shell
export TERMINAL='alacritty'
export MAN_POSIXLY_CORRECT 1
#+end_src


* greeting
#+begin_src shell
set -Ux fish_greeting "" # disable default welcome message
#+end_src
* test timestamp and keybinding
https://fishshell.com/docs/current/cmds/function.html
https://fishshell.com/docs/current/cmds/commandline.html

#+begin_src shell
function insert_timestamp --description 'Insert literal date command'
    commandline -i '$(date +%Y%m%d-%H%M%S)'
end

bind ctrl-t insert_timestamp
#+end_src
* stuff that should be at the end
#+begin_src shell
source ~/.config/fish/nnn.fish
#+end_src

#+begin_src shell
starship init fish | source
zoxide init fish | source
#+end_src
