[global]
    frame_color = "#3a94c5"

[urgency_low]
    background = "#eae4ca"
    foreground = "#5c6a72"

[urgency_normal]
    background = "#f3ead3"
    foreground = "#5c6a72"

[urgency_critical]
    background = "#f85552"
    foreground = "#f3ead3"
