#!/usr/bin/env ruby

# The famous "get a menu of emojis to copy" script. Now for Wayland and in Ruby.

choice = `cut -d ';' -f1 ~/.config/i3/resources/chars/* | wmenu -i -l 25 -p 'select emoji/unicode' | sed "s/ .*//"`
notify_settings = '--icon=dialog-information --expire-time 4000'

if choice.empty?
  `notify-send #{notify_settings} Emoji 'no emoji chosen'`
else
  IO.popen('wl-copy', 'w') do |pipe|
    pipe.puts choice
    pipe.close_write
  end
  system("notify-send #{notify_settings} Emoji 'Copied to clipboard: #{choice}' &")
end
