[[language]]
name = "nix"
# language-servers = ["nixd","nil"]
language-servers = ["nixd"]

[language-server.nixd]
command = "nixd"

[[language]]
name = "clojure"
language-servers = ["clojure-lsp"]
auto-format = true

[language-server.clojure-lsp]
command = "clojure-lsp"
