[global]
    frame_color = "#6a4dff"

[urgency_low]
    background = "#f1ece4"
    foreground = "#93836c"

[urgency_normal]
    background = "#f7f3ee"
    foreground = "#605a52"

[urgency_critical]
    background = "#f00000"
    foreground = "#f7f3ee"
