[global]
    frame_color = "#219fd5"

[urgency_low]
    background = "#0b2942"
    foreground = "#d6deeb"

[urgency_normal]
    background = "#011627"
    foreground = "#d6deeb"

[urgency_critical]
    background = "#ef5350"
    foreground = "#011627"
