# Everforest Dark Hard color theme for foot
# https://github.com/sainnhe/everforest

[colors]
background=272e33
foreground=d3c6aa
cursor=d3c6aa 83c092

regular0=2e383c
regular1=e67e80
regular2=a7c080
regular3=dbbc7f
regular4=7fbbb3
regular5=d699b6
regular6=83c092
regular7=d3c6aa

bright0=7a8478
bright1=e67e80
bright2=a7c080
bright3=dbbc7f
bright4=7fbbb3
bright5=d699b6
bright6=83c092
bright7=9da9a0
