[global]
    frame_color = "#3B6EA8"

[urgency_low]
    background = "#D8DEE9"
    foreground = "#3B4252"

[urgency_normal]
    background = "#E5E9F0"
    foreground = "#3B4252"

[urgency_critical]
    background = "#99324B"
    foreground = "#E5E9F0"
