# Modus Vivendi color theme for btop
# https://protesilaos.com/emacs/modus-themes

theme[main_bg]=""
theme_background=false
theme[main_fg]="#FFFFFF"
theme[title]="#00BCFF"
theme[hi_fg]="#6AE4B9"
theme[selected_bg]="#535353"
theme[selected_fg]="#FFFFFF"
theme[inactive_fg]="#646464"
theme[graph_text]="#FFFFFF"
theme[meter_bg]="#1E1E1E"
theme[proc_misc]="#6AE4B9"

theme[cpu_box]="#646464"
theme[mem_box]="#646464"
theme[net_box]="#646464"
theme[proc_box]="#646464"
theme[div_line]="#646464"

theme[temp_start]="#44BC44"
theme[temp_mid]="#D0BC00"
theme[temp_end]="#FF5F59"

theme[cpu_start]="#2FAFEF"
theme[cpu_mid]="#00BCFF"
theme[cpu_end]="#1F2F8F"

theme[free_start]="#1E1E1E"
theme[free_mid]="#00BCFF"
theme[free_end]="#6AE4B9"

theme[cached_start]="#303030"
theme[cached_mid]="#535353"
theme[cached_end]="#00BCFF"

theme[available_start]="#44BC44"
theme[available_mid]="#6AE4B9"
theme[available_end]="#00D3D0"

theme[used_start]="#44BC44"
theme[used_mid]="#D0BC00"
theme[used_end]="#FF5F59"

theme[download_start]="#2FAFEF"
theme[download_mid]="#00BCFF"
theme[download_end]="#6AE4B9"

theme[upload_start]="#FF6B55"
theme[upload_mid]="#FF5F59"
theme[upload_end]="#D0BC00"

theme[process_start]="#44BC44"
theme[process_mid]="#6AE4B9"
theme[process_end]="#FEACD0"
