[global]
    frame_color = "#00BCFF"

[urgency_low]
    background = "#1E1E1E"
    foreground = "#989898"

[urgency_normal]
    background = "#000000"
    foreground = "#FFFFFF"

[urgency_critical]
    background = "#9D1F1F"
    foreground = "#FFFFFF"
