[global]
    frame_color = "#603d3a"

[urgency_low]
    background = "#dfdfdf"
    foreground = "#595959"
    highlight = "#603d3a"

[urgency_normal]
    background = "#ededed"
    foreground = "#202020"
    highlight = "#603d3a"

[urgency_critical]
    background = "#a01010"
    foreground = "#ededed"
    highlight = "#ededed"
