[global]
    frame_color = "#603d3a"

[urgency_low]
    background = "#dfdfdf"
    foreground = "#595959"

[urgency_normal]
    background = "#ededed"
    foreground = "#202020"

[urgency_critical]
    background = "#a01010"
    foreground = "#ededed"
