[global]
    frame_color = "#c586ba"

[urgency_low]
    background = "#302f3c"
    foreground = "#a694b1"

[urgency_normal]
    background = "#221832"
    foreground = "#e2d7e7"

[urgency_critical]
    background = "#eca28f"
    foreground = "#221832"
