[global]
    frame_color = "#EB64B9"

[urgency_low]
    background = "#1B1720"
    foreground = "#FFFFFF"

[urgency_normal]
    background = "#27212E"
    foreground = "#FFFFFF"

[urgency_critical]
    background = "#FFB85B"
    foreground = "#1B1720"
