[global]
    frame_color = "#00e57a"

[urgency_low]
    background = "#011f11"
    foreground = "#00b25f"

[urgency_normal]
    background = "#000000"
    foreground = "#00b25f"

[urgency_critical]
    background = "#00ff88"
    foreground = "#000000"
