[global]
    frame_color = "#faa968"

[urgency_low]
    background = "#00172e"
    foreground = "#a7c9c6"
    highlight = "#faa968"

[urgency_normal]
    background = "#00172e"
    foreground = "#f6dcac"
    highlight = "#faa968"

[urgency_critical]
    background = "#f85525"
    foreground = "#f6dcac"
    highlight = "#f6dcac"
