[global]
    frame_color = "#faa968"

[urgency_low]
    background = "#00172e"
    foreground = "#a7c9c6"

[urgency_normal]
    background = "#05182e"
    foreground = "#f6dcac"

[urgency_critical]
    background = "#f85525"
    foreground = "#f6dcac"
