# -*- conf -*-
#
# Retro-82 color theme for foot

[colors-dark]
background=00172e
foreground=f6dcac
cursor=00172e f6dcac
selection-background=faa968
selection-foreground=00172e

regular0=00172e
regular1=f85525
regular2=028391
regular3=e97b3c
regular4=faa968
regular5=3f8f8a
regular6=8cbfb8
regular7=a7c9c6

bright0=57898a
bright1=f97751
bright2=35a2a7
bright3=ed9563
bright4=fbb986
bright5=65a5a1
bright6=a3ccc6
bright7=f6dcac
