[global]
    frame_color = "#e68e0d"

[urgency_low]
    background = "#333333"
    foreground = "#bebebe"
    highlight = "#e68e0d"

[urgency_normal]
    background = "#1e1e1e"
    foreground = "#bebebe"
    highlight = "#e68e0d"

[urgency_critical]
    background = "#660d0d"
    foreground = "#ffffff"
    highlight = "#ffffff"
