[global]
    frame_color = "#33859e"

[urgency_low]
    background = "#11151c"
    foreground = "#99d1ce"

[urgency_normal]
    background = "#091f2e"
    foreground = "#99d1ce"

[urgency_critical]
    background = "#c23127"
    foreground = "#99d1ce"
