[global]
    frame_color = "#84a0c6"

[urgency_low]
    background = "#1e2132"
    foreground = "#c6c8d1"

[urgency_normal]
    background = "#161821"
    foreground = "#c6c8d1"

[urgency_critical]
    background = "#e27878"
    foreground = "#161821"
