# restart hypridle for changes to take effect

# https://wiki.hypr.land/Hypr-Ecosystem/hypridle/
general {
    lock_cmd = swaylock --color 000000
}

listener {
    timeout = 1190
    on-timeout = notify-send "Locking screen in 10 seconds"
    #on-resume = notify-send "Welcome back!"
}

listener {
    timeout = 1200
    on-timeout = loginctl lock-session
    #on-resume = notify-send "Welcome back!"
}

# TODO 2026-04: on ax-bee, sometimes I can't wake up the monitors at all anymore,
#               no TTY switching, nothing - a hard reset is the only out
listener {
    timeout = 1230
    on-timeout = hyprctl dispatch dpms off    # screen off when timeout has passed
    on-resume = hyprctl dispatch dpms on      # screen on when activity is detected after timeout has fired.
}
