#  --------------------------------------------------------------
#  MODE OPEN
#  --------------------------------------------------------------

# keychord like sxhkd: https://wiki.hypr.land/Configuring/Binds/#submaps
bind = $mainMod, O, submap, applications
# start submap
submap = applications

binde = , b, exec, foot -T bluetui bluetui
binde = , b, submap, reset

binde = , c, exec, qalculate-gtk
binde = , c, submap, reset

# one press `e` is enough to launch and reset
binde = , e, exec, emacsclient -c
# use reset to go back to the global submap
binde = , e, submap, reset

binde = , f, exec, $fileManager
binde = , f, submap, reset

binde = , k, exec, keepassxc
binde = , k, submap, reset

binde = , m, exec, emacs --name ax-emacs-emms --eval '(ax/open-emms-layout)'
binde = , m, submap, reset

binde = , p, exec, pavucontrol
binde = , p, submap, reset

binde = , q, exec, qbittorrent
binde = , q, submap, reset

binde = , v, exec, brave
binde = , v, submap, reset

binde = , w, exec, foot -T wiremix wiremix
binde = , w, submap, reset

binde = , x, exec, firefox
binde = , x, submap, reset

# the default way shown in the docs is tedious, but makes sense to have in addition
bind = , escape, submap, reset
# reset the submap, which will return to the global submap
submap = reset


#  --------------------------------------------------------------
#  MODE CHANGE
#  --------------------------------------------------------------

bind = $mainMod, C, submap, change
submap = change

binde = , l, exec, $HOME/syscfg/scripts/bb/licht.clj
binde = , l, submap, reset
binde = , w, exec, $HOME/syscfg/scripts/bb/set_random_wallpaper.clj
binde = , w, submap, reset
binde = , x, exec, killall swaybg
binde = , x, submap, reset

bind = , escape, submap, reset

submap = reset


#  --------------------------------------------------------------
#  MODE TOGGLE
#  --------------------------------------------------------------
bind = $mainMod, t, submap, change
submap = change

# toggle bluetooth
binde = , b, exec, rfkill toggle bluetooth
binde = , b, submap, reset


bind = , escape, submap, reset
submap = reset


#  --------------------------------------------------------------
#  MODE X
#  --------------------------------------------------------------

bind = $mainMod, X, submap, x
submap = x

# Screenshot - all
binde = , a, exec, grim - | swappy -f -
binde = , a, submap, reset
# Screenshot - select
binde = , s, exec, grim -g "$(slurp)" - | swappy -f -
binde = , s, submap, reset
# Screenshot - window
binde = , w, exec, hyprctl activewindow -j | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"' | grim -g - - | swappy -f -
binde = , w, submap, reset

bind = , escape, submap, reset

submap = reset

