[global]
    frame_color = "#8d8d8d"

[urgency_low]
    background = "#000000"
    foreground = "#b0b0b0"
    highlight = "#ffffff"

[urgency_normal]
    background = "#000000"
    foreground = "#ffffff"
    highlight = "#ffffff"

[urgency_critical]
    background = "#ffffff"
    foreground = "#000000"
    highlight = "#000000"
