# -*- conf -*-
#
# Vantablack color theme for foot

[colors]
background=000000
foreground=ffffff
cursor=000000 ffffff
selection-background=ffffff
selection-foreground=000000

regular0=404040
regular1=a4a4a4
regular2=b6b6b6
regular3=cecece
regular4=8d8d8d
regular5=9b9b9b
regular6=b0b0b0
regular7=ececec

bright0=5c5c5c
bright1=a4a4a4
bright2=b6b6b6
bright3=cecece
bright4=8d8d8d
bright5=9b9b9b
bright6=b0b0b0
bright7=ffffff
