[global]
    frame_color = "#8FD4FF"

[urgency_low]
    background = "#0E1926"
    foreground = "#B0CCDC"

[urgency_normal]
    background = "#000000"
    foreground = "#B0CCDC"

[urgency_critical]
    background = "#DEB45B"
    foreground = "#000000"
