[global]
    frame_color = "#88C0D0"

[urgency_low]
    background = "#3B4252"
    foreground = "#D8DEE9"

[urgency_normal]
    background = "#2E3440"
    foreground = "#D8DEE9"

[urgency_critical]
    background = "#BF616A"
    foreground = "#ECEFF4"
