[global]
    frame_color = "#6e6e6e"

[urgency_low]
    background = "#ffffff"
    foreground = "#3a3a3a"

[urgency_normal]
    background = "#ffffff"
    foreground = "#000000"

[urgency_critical]
    background = "#000000"
    foreground = "#ffffff"
