[global]
    frame_color = "#adade0"

[urgency_low]
    background = "#3a3c4c"
    foreground = "#aea6b8"
    highlight = "#adade0"

[urgency_normal]
    background = "#2a283d"
    foreground = "#edf0f8"
    highlight = "#adade0"

[urgency_critical]
    background = "#eca28f"
    foreground = "#2a283d"
    highlight = "#2a283d"
